FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json

RUN npm ci

COPY . .

RUN npm run prisma:generate --workspace apps/api
RUN npm run build --workspace apps/api

EXPOSE 3000

CMD ["sh", "-c", "npm run prisma:push --workspace apps/api && npm run start --workspace apps/api"]
